### ISSUE TITLE
UCF_Page_Assets_Common::enqueue_assets() throws notices if global $post is not set

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Page-Assets-Plugin#10]
`Notice: Trying to get property of non-object in UCF-Page-Assets-Plugin/includes/page-assets-common.php`; lines 16 and 17

https://github.com/UCF/UCF-Page-Assets-Plugin/blob/master/includes/page-assets-common.php#L16-L17

We need to ensure the global `$post` object actually exists and is a valid `WP_Post` object before accessing post IDs on these two lines.  For instance, on a site's 404 template, `$post` will be null.

**Comment by jmbarne3** [comment]
Solved by #12
