### ISSUE TITLE
CSS/JS files are not unset from attached posts when deleted from the media library

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Page-Assets-Plugin#5]
After manually removing a CSS or JS file from the media library, custom CSS/JS fields still reference the deleted attachment IDs.

**Comment by jmbarne3** [comment]
We can look into querying for posts with this attachment ID as a value for CSS or JS whenever the attachment is deleted ([using this hook](https://codex.wordpress.org/Plugin_API/Action_Reference/delete_attachment)) then set the meta data to null.
